language: erlang
dist: xenial
otp_release:
  - "22.2"
addons:
  apt:
    packages:
      - uuid-dev
install:
  - wget https://github.com/erlang/rebar3/releases/download/3.14.1/rebar3
  - chmod +x rebar3
script:
  - ./rebar3
cache:
  directories:
    - _build
